name: Run test examples

on: [push]

jobs:
  all-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Set up Python 3.x
      uses: actions/setup-python@v2

    - name: Install dependencies
      run: pip install -r ./requirements.txt

    - name: pwd
      run: pwd
    - name: Run robot tests
      run: robot --pythonpath . --listener allure_robotframework ./robot_tests/